name: mob_pizza_mobile
description: Mob Pizza â€“ Flutter mobile app (mob/speakeasy theme)
publish_to: "none"
version: 0.1.0+7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.1
  go_router: ^14.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mobpizza_zoomedout_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0B0C10"
  adaptive_icon_foreground: "assets/images/mobpizza_zoomedout_logo.png"
  adaptive_icon_padding: true

